python playlist.py waerloga9000 3xHMNdkx6aY5JORnBs4lg3 playlists/brianEDMPlaylist.csv
python playlist.py waerloga9000 7vNQs0SuAd8NTNDu2v9fd4 playlists/brianJPandKRHipHop.csv
python playlist.py Spotify 37i9dQZF1DWZUAeYvs88zc playlists/spotifySadBops.csv
python playlist.py Spotify 37i9dQZF1DX1lVhptIYRda playlists/spotifyHotCountry.csv
python playlist.py Spotify 37i9dQZF1DX4SBhb3fqCJd playlists/spotifyRAndB.csv
python playlist.py Spotify 37i9dQZF1DWXRqgorJj26U playlists/spotifyRockClassics.csv
python playlist.py Spotify 37i9dQZF1DXcRXFNfZr7Tp playlists/spotifyJustHits.csv 